accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "MPL-2.0",
    "ISC",
    "Unicode-3.0",
    "BSL-1.0",
    "Unicode-DFS-2016",
    "CDLA-Permissive-2.0",
    "Zlib",
    "Apache-2.0 WITH LLVM-exception",
    "0BSD",
    "BSD-2-Clause",
    "NCSA",
    "CC0-1.0",
    "OpenSSL"
]
